Teacher_Best/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth.urls import path
from . import settings
from templates.admin import views
from admin_notification.views import check_notification_view

urlpatterns = [
    path('admin/login/', views.LoginView.as_view()),
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('accounts/' , include('django.contrib.auth.urls')),
    path('account/', include("account.urls")),
    path('articles/', include("post.urls")),
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('check/notification', check_notification_view, name="check_notifications"),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from . import views
from django.urls import path

app_name = 'account'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name="login"),
    path('register/', views.RegisterView.as_view(), name="register"),
    path('Profile/user/', views.ProfileView.as_view(), name="profile"),
    path('Panel/user/', views.PanelUserView.as_view(), name="panel_user"),
    path('Panel/edit/', views.PanelEditView.as_view(), name="panel_edit"),
    path('Panel/update/<int:pk>', views.PanelUpdate.as_view(), name="panel_update"),
    path('Panel/Delete/<int:pk>', views.PanelDelete.as_view(), name="panel_Delete"),
    path('logout/', views.logout_view, name="logout"),
]

home/urls.py
from . import views
from django.urls import path


app_name = "home"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
]

templates/include/footer.html
{% load static %}

{# footer #}
<footer class="main-footer">
    <div class="float-left">
        <strong>هرگونه کپی برداری حرام است</strong>&copy;
    </div>
</footer>
{# footer #}

<!-- jQuery -->
<script src="{% static "adminlte/plugins/jquery/jquery.min.js" %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static "adminlte/plugins/jquery-ui/jquery-ui.min.js" %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 rtl -->
<script src="https://cdn.rtlcss.com/bootstrap/v4.2.1/js/bootstrap.min.js"></script>
<!-- Bootstrap 4 -->
<script src="{% static "adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
<!-- ChartJS -->
<script src="{% static "adminlte/plugins/chart.js/Chart.min.js" %}"></script>
<!-- Sparkline -->
<script src="{% static "adminlte/plugins/sparklines/sparkline.js" %}"></script>
<!-- JQVMap -->
<script src="{% static "adminlte/plugins/jqvmap/jquery.vmap.min.js" %}"></script>
<script src="{% static "adminlte/plugins/jqvmap/maps/jquery.vmap.world.js" %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static "adminlte/plugins/jquery-knob/jquery.knob.min.js" %}"></script>
<!-- daterangepicker -->
<script src="{% static "adminlte/plugins/moment/moment.min.js" %}"></script>
<script src="{% static "adminlte/plugins/daterangepicker/daterangepicker.js" %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static "adminlte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js" %}"></script>
<!-- Summernote -->
<script src="{% static "adminlte/plugins/summernote/summernote-bs4.min.js" %}"></script>
<!-- overlayScrollbars -->
<script src="{% static "adminlte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js" %}"></script>
<!-- AdminLTE App -->
<script src="{% static "adminlte/dist/js/adminlte.js" %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static "adminlte/dist/js/pages/dashboard.js" %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static "adminlte/dist/js/demo.js" %}"></script>

templates/include/header.html
{% load static %}

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>{% block title %}پنل کاربر{% endblock %}</title>
<link rel="shortcut icon" type="image/x-icon" href="{% static "img/photo.jpg" %}">
<!-- Tell the browser to be responsive to screen width -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Font Awesome -->
<link rel="stylesheet" href="{% static "adminlte/plugins/fontawesome-free/css/all.min.css" %}">
<!-- Ionicons -->
<link rel="stylesheet" href="{% static "https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" %}">
<!-- Tempusdominus Bbootstrap 4 -->
<link rel="stylesheet"
      href="{% static "adminlte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css" %}">
<!-- iCheck -->
<link rel="stylesheet" href="{% static "adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css" %}">
<!-- JQVMap -->
<link rel="stylesheet" href="{% static "adminlte/plugins/jqvmap/jqvmap.min.css" %}">
<!-- Theme style -->
<link rel="stylesheet" href="{% static "adminlte/dist/css/adminlte.min.css" %}">
<!-- overlayScrollbars -->
<link rel="stylesheet" href="{% static "adminlte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css" %}">
<!-- Daterange picker -->
<link rel="stylesheet" href="{% static "adminlte/plugins/daterangepicker/daterangepicker.css" %}">
<!-- summernote -->
<link rel="stylesheet" href="{% static "adminlte/plugins/summernote/summernote-bs4.css" %}">
<!-- Bootstrap 4 RTL -->
<link rel="stylesheet" href="https://cdn.rtlcss.com/bootstrap/v4.2.1/css/bootstrap.min.css">
<!-- Custom style for RTL -->
<link rel="stylesheet" href="{% static "adminlte/dist/css/custom.css" %}">
<link rel="stylesheet" href="{% static "css/font-vazir.css" %}">

templates/include/login-register.html
{% load static %}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>{% block register %}ورود | ثبت نام{% endblock %}</title>
<link rel="shortcut icon" type="image/x-icon" href="{% static "img/photo.jpg" %}">
<!-- Tell the browser to be responsive to screen width -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Font Awesome -->
<link rel="stylesheet" href="{% static "adminlte/plugins/fontawesome-free/css/all.min.css" %}">
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<!-- icheck bootstrap -->
<link rel="stylesheet" href="{% static "adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css" %}">
<!-- Theme style -->
<link rel="stylesheet" href="{% static "adminlte/dist/css/adminlte.min.css" %}">
<!-- style -->
<link rel="stylesheet" href="{% static "css/style_login_register.css" %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
<style>
    @font-face {
        font-family: Vazir;
        font-style: normal;
        font-weight: normal;
        src: url('{% static "fonts/Vazir.eot" %}');
        src: url('{% static "fonts/Vazir.eot?#iefix" %}') format('embedded-opentype'),
        url('{% static "fonts/Vazir.woff2" %}') format('woff2'),
        url('{% static "fonts/Vazir.woff" %}') format('woff'),
        url('{% static "fonts/Vazir.ttf" %}') format('truetype');
    }

    @font-face {
        font-family: Vazir;
        font-style: normal;
        font-weight: bold;
        src: url('{% static "fonts/Vazir-Bold.eot" %}');
        src: url('{% static "fonts/Vazir-Bold.eot?#iefix" %}') format('embedded-opentype'),
        url('{% static "fonts/Vazir-Bold.woff2" %}') format('woff2'),
        url('{% static "fonts/Vazir-Bold.woff" %}') format('woff'),
        url('{% static "fonts/Vazir-Bold.ttf" %}') format('truetype');
    }

    body {
        font-family: 'Vazir', Arial, sans-serif;
        font-weight: bold;
    }
</style>

<!-- jQuery -->
<script src="{% static "adminlte/plugins/jquery/jquery.min.js" %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static "adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
<script>
    function register() {
        let pass = document.getElementById('pass');
        let pass2 = document.getElementById('pass2');
        if (document.getElementById('check').checked) {
            pass.setAttribute('type', 'text');
            pass2.setAttribute('type', 'text');
        } else {
            pass.setAttribute('type', 'password');
            pass2.setAttribute('type', 'password');
        }
    }
</script>
<script>
    function login() {
        let pass = document.getElementById('pass');
        if (document.getElementById('check').checked) {
            pass.setAttribute('type', 'text');
        } else {
            pass.setAttribute('type', 'password');
        }
    }
</script>

templates/include/sidebar.html
{% load static %}
{% block html %}
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="{% url "home:home" %}" class="brand-link">
            <img src="{% static "img/photo.jpg" %}" alt="AdminLTE Logo"
                 class="brand-image img-circle elevation-3"
                 style="opacity: .8">
            <span class="brand-text font-weight-light">معلم یاد</span>
        </a>
        <div class="sidebar">
            <!-- Sidebar user panel (optional) -->
            <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                {% if request.user.image.url != None %}
                    <div class="text-center">
                        <img class="profile-user-img img-fluid img-circle"
                             src="{{ request.user.image.url }}"
                             alt="User profile picture">
                    </div>
                {% else %}
                    <div class="text-center">
                        <img class="profile-user-img img-fluid img-circle"
                             src="{% static "img/profile.jpg" %}"
                             alt="User profile picture">
                    </div>
                {% endif %}
                <div class="info">
                    <a href="{% url "account:profile" %}" class="d-block">{{ request.user.email }}</a>
                </div>
            </div>

            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                    data-accordion="false">
                    <li class="nav-item has-treeview menu-open">
                        <a href="#" class="nav-link active">
                            <i class="nav-icon fas fa-tachometer-alt"></i>
                            <p>
                                افزودن
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{% url "account:panel_user" %}"
                                   class="nav-link {% if request.resolver_match.url_name == "panel_user" %}active{% endif %}">
                                    <i class="fa fa-table nav-icon"></i>
                                    <p>لیست</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url "account:panel_edit" %}"
                                   class="nav-link {% if request.resolver_match.url_name == "panel_edit" %}active{% endif %}">
                                    <i class="fa fa-edit nav-icon"></i>
                                    <p>افزودن</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a href="{% url "account:profile" %}"
                           class="nav-link {% if request.resolver_match.url_name == "profile" %}active{% endif %}">
                            <i class="nav-icon fa fa-user-astronaut"></i>
                            <p>
                                پروفایل
                            </p>
                        </a>
                    </li>
                    {% if user.is_admin %}
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fa fa-star"></i>
                                <p>
                                    vip
                                    <span class="right badge badge-danger">New</span>
                                </p>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>
{% endblock %}