Teacher_Best/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth.urls import path
from . import settings
from templates.admin import views
from admin_notification.views import check_notification_view

urlpatterns = [
    path('admin/login/', views.LoginView.as_view()),
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('accounts/' , include('django.contrib.auth.urls')),
    path('account/', include("account.urls")),
    path('articles/', include("post.urls")),
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('check/notification', check_notification_view, name="check_notifications"),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from . import views
from django.urls import path


app_name = "home"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
]

post/urls.py
from . import views
from django.urls import path


app_name = 'post'

urlpatterns = [
    path('list/', views.ListDetailView.as_view(), name='Detail'),
    path('<int:pk>/', views.DetailView.as_view(), name='user_Detail'),
    path('like/<int:id>/<int:pk>' , views.like , name='like'),
    path('Search/', views.SearchListView, name='search'),
]

post/models.py
from django.db import models
from account.models import User
from teacher.models import Teacher
class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='likes')
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='likes')

    def __str__(self):
        return f'{self.teacher.username} - {self.user.email}'

    class Meta:
        verbose_name = "لایک"
        verbose_name_plural = "لایک ها"
        ordering = ('-user',)

post/views.py
from django.core.paginator import Paginator
from django.shortcuts import redirect, render
from django.views.generic import ListView, DetailView
from teacher.models import Teacher
from .models import Like
from hitcount.views import HitCountDetailView
from django.db.models import Q
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank


class ListDetailView(ListView):
    model = Teacher
    paginate_by = 6
    ordering = ('-is_teacher',)
    queryset = Teacher.objects.filter(is_teacher=True)
    template_name = 'post/list_detail.html'


class DetailView(HitCountDetailView, DetailView):
    model = Teacher
    template_name = 'post/detail.html'
    count_hit = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            if self.request.user.likes.filter(teacher__username=self.object.username,
                                              user_id=self.request.user.id).exists():
                context['is_like'] = True
            else:
                context['is_like'] = False
        return context


def SearchListView(request):
    q = request.GET.get('q')
    teacher = Teacher.objects.filter(Q(name_field__icontains=q) | Q(discription__icontains=q))
    # vector = SearchVector("name_field", "discription")
    # query = SearchQuery(q, search_type='websearch')
    # teacher = Teacher.objects.annotate(search=vector, rank=SearchRank(vector, query)).filter(search=query).order_by("-rank")
    page_number = request.GET.get('page')
    paginator = Paginator(teacher, 3)
    object_list = paginator.get_page(page_number)
    return render(request, 'post/list_detail.html', {"object_list": object_list, "page_obj": object_list})


def like(request, id, pk):
    if request.user.is_authenticated:
        try:
            like = Like.objects.get(teacher__id=id, user_id=request.user.id)
            like.delete()
        except:
            Like.objects.create(teacher_id=pk, user_id=request.user.id)
        return redirect('post:user_Detail', pk)
    return redirect("account:login")

post/templates/post/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}معلم یاد{% endblock %}</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static "img/photo.jpg" %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static "css/bootstrap.rtl.min.css" %}">
    <link rel="stylesheet" href="{% static "css/styles.css" %}">
    <link rel="stylesheet" href="{% static "css/hearts.css" %}">
    <!-- font web -->
    <link rel="stylesheet" href="{% static "css/font-vazir.css" %}">
</head>
<body>
<div class="text-center">
    <a href="{% url "post:Detail" %}" data-page-no="2" class="btn btn-primary tm-intro-btn tm-page-link">
        برگشت به صفحه قبلی
    </a>
</div>

<div class="card resize">
    <img src="{{ object.image.url }}" class="card-img">
    <div class="card-header">
        <h4 class="card-title"> نام: {{ object.username }}</h4>
        <h5 class="card-title">پایه: {{ object.Foundation }}</h5>
        <h5 class="card-comment"> رشته تدریس: {{ object.name_field }}</h5>
        {% if object.entrance %}<h5 class="card-comment">رتبه کنکور: {{ object.entrance }}</h5>{% else %}{% endif %}
        <h5 class="card-comment"> دانشگاه: {{ object.university }}</h5>
        <h5 class="card-comment"> مدرک: {{ object.evidence }}</h5>
        <h5 class="card-comment"> سابقه تدریس: {{ object.teaching }}</h5>
    </div>
    <div class="card-body">
        <p class="card-text">{{ object.discription|safe }} {% if object.view_resume %}<a class="text text-primary"
                                                                                           href="{{ object.view_resume.url }}">مشاهده
            رزومه</a>{% else %}{% endif %}</p>
    </div>
    <div class="card-footer">
        <small class="text-muted">تاریخ ایجاد: {{ object.get_jalali_data }}</small>
        <div class="heart">
            {% if is_like %}
                <a href="{% url 'post:like' teacher.id teacher.pk %}" class="fa fa-heart" id="heart"><span
                        id="count">{{ teacher.likes.all.count }}</span></a>
            {% else %}
                <a href="{% url 'post:like' teacher.id teacher.pk %}" class="fa fa-heart-o" id="heart"><span
                        id="count">{{ teacher.likes.all.count }}</span></a>
            {% endif %}
        </div>
    </div>
    <ion-icon name="heart-circle-outline"></ion-icon>
</div>

<script src="{% static "js/bootstrap.bundle.min.js" %}"></script>
<script src="{% static "js/jquery-3.5.1.min.js" %}"></script>
<script>
    function like(id, pk) {
        let element = document.getElementById("heart")
        let count = document.getElementById("count")
        $.get(`/Post/like/${id}/${pk}`).then(response => {
            if (response['response'] === "liked") {
                element.className = 'fa fa-heart'
                count.innerText = Number(count.innerText) + 1
            } else {
                element.className = 'fa fa-heart-o'
                count.innerText = Number(count.innerText) - 1
            }
        })
    }
</script>
</body>
</html>

post/templates/post/list_detail.html
{% load static %}
{% load hitcount_tags %}
{% load ratings %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}معلم یاد{% endblock %}</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static "img/photo.jpg" %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
    <link rel="stylesheet" href="{% static "css/bootstrap.rtl.min.css" %}">
    <link rel="stylesheet" href="{% static "css/styles.css" %}">
    <!-- font web -->
    <link rel="stylesheet" href="{% static "css/font-vazir.css" %}">
</head>
<body class="container">
<video autoplay muted loop id="bg-video">
    <source src="{% static "video/books.mp4" %}" type="video/mp4">
</video>

<div class="text-center">
    <a href="{% url "home:home" %}" data-page-no="2" class="btn btn-primary tm-intro-btn tm-page-link">
        برگشت به صفحه قبلی
    </a>
</div>

<form class="d-flex search form-floating naviget" method="get" action="{% url 'post:search' %}">
    <input class="form-control me-2" id="searchuser" name="q" type="search" aria-label="Search"
           placeholder="searchuser">
    <label for="searchuser">جست و جو...!؟</label>
    <!-- <button class="btn btn-primary" type="submit"><img src="img/search_black_18dp.svg"></button> -->
</form>

<div class="row row-cols-1 row-cols-md-3 g-4 style">
    {% for teacher in object_list %}
        {% if teacher.is_teacher %}
            <div class="col">
                <div class="card">
                    <img src="{{ teacher.image.url }}" class="img-fluid" alt="img">
                    <div class="card-header">
                        <h5 class="card-title">{{ teacher.username }}</h5>
                        <h6 class="card-subtitle">{{ teacher.name_field }}</h6>
                        <span class="text-bold text-danger"> بازدید: {% get_hit_count for teacher %}</span>
                    </div>
                    <div class="row-cols-auto"><div class="card-footer">{% ratings teacher %}</div></div>
                    <div class="card-body">
                        <p class="card-text">{{ teacher.discription|striptags|truncatechars:20 }}
                            <a href="{% url "post:user_Detail" teacher.pk %}" class="btn btn-outline-primary">ادامه
                                مطلب</a>
                        </p>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}
</div>

<nav aria-label="Page navigation example">
    {% if page_obj.has_other_pages %}
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=
                            {{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"
                       tabindex="-1"
                       aria-disabled="true">قبلی</a>
                </li>
            {% endif %}
            {% for item in page_obj.paginator.page_range %}
                {% if page_obj.number == item %}
                    <li class="page-item active"><a class="page-link" href="?page=
                            {{ item }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ item }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page=
                            {{ item }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ item }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page=
                    {{ page_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">بعدی</a>
                </li>
            {% endif %}
        </ul>
    {% endif %}
</nav>

<script src="{% static "js/bootstrap.bundle.min.js" %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
</body>
</html>